---
  main:
    --print_frequency: '200'
  training:

  dataset:
    --train_datasets:
      - scoutval
    --detection_threshold: "0.5"
    --split_proportion: '0.9'
    --metric_threshold: '1'

  model:

  loss:
