version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s.%(msecs)03d - [%(shortpath)38s:%(lineno)03d] - %(levelname)-8s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
  colored_console:
    (): 'coloredlogs.ColoredFormatter'
    format: "%(asctime)s.%(msecs)03d - [%(shortpath)38s:%(lineno)03d] - %(levelname)-8s - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
    field_styles:
      asctime: {color: 'green'}
      hostname: {color: 'magenta'}
      levelname: {color: 'white', bold: True}
      name: {color: 'blue'}
      programname: {color: 'cyan'}

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: colored_console
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: ./debug.log
    encoding: utf8

root:
  level: WARNING
  handlers: [console]

loggers:
    pose_estimation:
        level: DEBUG
        handlers: [console]
        propagate: no
